name: Mainline CI

on:
  push:
    branches:
      - master
      - main

jobs:
  mainline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Print Commit Message
        run: |
          COMMIT_SHA=$(git rev-parse --short HEAD)
          echo "Job triggered by commit $COMMIT_SHA"
          echo "Hello, this is your custom message!"
